# Generated by Django 4.2.7 on 2023-11-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dataNasc',
            field=models.CharField(max_length=255),
        ),
    ]
