# Generated by Django 4.2.6 on 2023-11-30 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='cartao',
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_emprest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.IntegerField()),
                ('valor_parcelas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pendente', max_length=20)),
                ('dataVenc', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_conta', to='api.conta')),
            ],
        ),
    ]
