# Generated by Django 4.2.6 on 2023-12-01 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_transacao_cartao_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_try_login',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_try_login',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
